### ISSUE TITLE
Create a token balance page for the application and connect it to the database

### ISSUE THREAD

**Issue by Gabriel19-00477** [Gabriel19-00477/Lazatech-Educate#23]

**Comment by BensonAtencio** [comment]
These are the screenshots of the codes from the token balance page html and ts

You can see that it is connected to the database since I call the username and token variables

Don't mind the buttons I'm just testing something

![Screenshot 2022-07-27 213122](https://user-images.githubusercontent.com/108327522/181259812-04632f22-9aa8-4f81-82fc-93440372f4e6.jpg)

![Screenshot 2022-07-27 213202](https://user-images.githubusercontent.com/108327522/181259820-f6e6182a-f7eb-489f-abf4-de7988dec310.jpg)

![Screenshot 2022-07-27 213234](https://user-images.githubusercontent.com/108327522/181259837-0436819e-cde1-4154-8fab-0c2c195cd2d5.jpg)

**Comment by Gabriel19-00477** [comment]
Thank you for the update!

**Comment by Gabriel19-00477** [comment]
Thanks. I will also update the database variables once I am finish working with the documentation of our project.
